### ISSUE TITLE
Provide makefile for libretro builds

### ISSUE THREAD

**Issue by ofry** [markwkidd/FreeIntv#1]
Provide makefile for libretro builds. It's necessary for build this core on libretro buildbot.

**Comment by markwkidd** [comment]
I've just added a new Makefile here: https://github.com/markwkidd/FreeIntv/blob/master/Makefile

It's based on the mame2003 Makefile, which is the libretro make process I'm most familiar with. Hopefully some of the boilerplate compilation flags for the various compilation targets will carry over from mame2003, so I left some of those relevant sections intact despite not being personally familiar with all of the flags involved.

Currently it compiles in Windows 7 via MinGW x64 and in Ubuntu, but crashes on both platforms when trying to load content.

**Comment by recompileorg** [comment]
This is from the Makefile RobLoach created for FreeJ2ME:

```
SOURCES_C += freej2me_libretro.c \
	deps/libretro-common/file/file_path.c \
	deps/libretro-common/compat/compat_strl.c \
	deps/libretro-common/compat/compat_strcasestr.c

SOURCES_CXX += 

INCLUDES += -Ideps/libretro-common/include
```

The comment was "Allow use of the System/BIOS directory"  which would explain the crashing.

**Comment by recompileorg** [comment]
Okay, I figured out what that was all about and now have, what should be, a Makefile usable just about everywhere, in combination with a few source changes.  I assumed the crashing on windows you reported was related to loading exec and grom, which this should fix.  I've made a pull request, though it also includes a few extras not related to this issue (updated instructions, some warnings fixed, etc.)

**Comment by KMFDManic** [comment]
@recompileorg 
These changes fixed things on my end a few days ago, which I submitted 2 days ago, to help you guys out.  We went on to do some of the same fixes you did to fix compiler warnings, and I can confirm things are shaping up, quite nicely.  Most games run great!  Only thing that would make things better would be controller overlays:)  Thanks to both of you:)  Loving the Core.

-strcat(execPath, "exec.bin");
-//printf("%s\n", execPath);
+strcat(execPath, "/exec.bin");^M
+printf("%s\n", execPath);^M

if path is /path/ it works
but if it's /path it doesn't work

in most cases
fopen/CreateFile will work, so command-line apps might not, but this doesn't use command-line interface

**Comment by markwkidd** [comment]
Hi @recompileorg thank you for taking the time to get set up on github. I will add you as a contributor to this repository in a moment so that you can make changes directly. @KMFDManic thanks for your work to get this up and running as well.

Please note that I have made a few tweaks after committing on the PR: sorting the RetroPie material into a folder, and adding back some logging for the path of the BIOS files that was in my prior version. You might want to pull these changes into your local git repository or do a fresh download of the source.

I don't plan on making any other changes soon unless something comes up in terms of the libretro core buildbot. Speaking of which, we've already got the core compiling for at least half a dozen platforms, all we need now is someone to help write recipes for the various android and the console ports. :)
